ukf_node:
  ros__parameters:  
    frequency: 15.0
    sensor_timeout: 1.9
    two_d_mode: false
    publish_tf: false
    # publish_tf: true #set to true if you want to launch the baselink-odom transformation.  The camera-base transformation is in the UKF launch file
    odom_frame: odom
    base_link_frame: base_link
    print_diagnostics: true

    pose0: /aruco_pose_0
    pose0_config: [true,  true,  true,     # x y z
              false,  false,  true,      #do we want yaw from aruco?
              false, false, false,    
              false, false, false,    
              false, false, false]
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 5
    pose0_rejection_threshold: 2.0

    pose1: /drive/pose/covariance
    pose1_config: [true,  true,  true,     # x y z
              false,  false,  true,     #only want yaw from drivetrain - IMU based
              false, false, false,    
              false, false, false,    
              false, false, false]
    pose1_differential: false
    pose1_relative: false
    pose1_queue_size: 5
    pose1_rejection_threshold: 2.0

    #imu0:               /imu/data   #another approach is to send the twist from drive here and then have the imu as a seperate subscription, could be more robust         
    #imu0_config:        [false, false, false,  
    #                    false, false,  true,   
    #                    false, false, false,   
    #                    false, false,  true,   
    #                    false, false, false]   

    #imu0_relative:      false                 
    #imu0_differential:  false                 
    #imu0_remove_gravitational_acceleration: true  
    #imu0_queue_size:    10                    
    #imu0_nodelay:       true                  
    #imu0_rejection_threshold: 0.8            
    #imu0_pose_rejection_threshold: 0.8        
    #imu0_twist_rejection_threshold: 0.8       
    #imu0_linear_acceleration_rejection_threshold: 5.0  
    